version: '3'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:21.3.20
    container_name: clickhouse
    restart: always
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: pansoft2022
    expose:
      - 9000
      - 8123
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/database:/var/lib/clickhouse
      - ./data/logs:/var/log
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./config/conf.d:/etc/clickhouse-server/conf.d
    # /etc/security/limits.conf
    ulimits:
      core: 655350
      nproc: 655350
      nofile: 262144
