services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: always
    environment:
      # Requested, set the root's password of MySQL service.
      - MYSQL_ROOT_PASSWORD=db_uat  
      - MYSQL_LOG_CONSOLE=true
    volumes:
      # Requested, specifies the path to MySQL data persistent store.
      - /data/seafile/seafile-mysql/db:/var/lib/mysql  
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    restart: always
    ports:
      - "80:80"
      # If https is enabled, cancel the comment.
      #- "443:443"  
    volumes:
      # Requested, specifies the path to Seafile data persistent store.
      - /data/seafile/seafile-data:/shared   
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_uat  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=d90F&zr66diwNON     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether use letsencrypt to generate cert.
      - SEAFILE_SERVER_HOSTNAME=seafile.example.com # Specifies your host name.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:
    ipam:
      driver: default
      config:
        - subnet: 162.28.0.0/16