version: '3.5'
services:
  consul:
    image: consul:1.14.3
    container_name: consul
    restart: always
    #-server运行的时候需要指定 data-dir
    command: consul agent -server -bootstrap -ui -data-dir=/consul/data -node=1 -client=0.0.0.0 
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_HTTP_ADDR=0.0.0.0
    expose:
      - 8500
      - 8600
    ports:
      - 8500:8500
      - 8600:8600
    volumes:
      - ./data/consul:/consul/data

    # /etc/security/limits.conf
    ulimits:
      core: 655350
      nproc: 655350
      nofile: 262144