version: '3.5'

services:
  # http://seata.io/zh-cn/docs/ops/deploy-by-docker-compose.html
  # chmod 777 /mnt/volume/seata
  seata:
    image: seataio/seata-server:1.4.2
    container_name: seata
    environment:
      # 指定seata服务启动端口
      - SEATA_PORT=8091
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务
      - SEATA_IP=192.168.123.22
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    restart: always
    #networks:
    #  gl-net:
    #    ipv4_address: 172.28.0.70
    volumes:
      # 因为registry.conf中是nacos配置中心，只需要把doc/seata/conf/registry.conf与file.conf放到/mnt/volume/seata/config文件夹中
      - ./conf:/root/seata-config
      - ./logs:/root/logs
    ports:
      - "8091:8091"

#docker network ls
#The actual name is volume_edu-net
#表示新建了 `172.28.0.0/16` 的网络，名称为 gl-net
#新建网络是为了实现同主机的多个容器间网络互通，走内网，类似于软件交换机
#networks:
#  gl-net:
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.0.0/16
#networks:
#  volume_gl-net:
#    external: true