version: '3.5'

services:
  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: nacos
    env_file:
      - ./env/nacos-standlone-mysql.env
    #command:
    restart: always
    #https://nacos.io/zh-cn/docs/quick-start-docker.html
    volumes:
      - ./logs/:/home/nacos/logs
    environment:
      - "MODE=standalone"
    #networks:
    #  gl-net:
    #    ipv4_address: 172.28.0.40
    ports:
      - 8848:8848
      - 9848:9848
      - 9555:9555

#docker network ls
#The actual name is volume_edu-net
#表示新建了 `172.28.0.0/16` 的网络，名称为 gl-net
#新建网络是为了实现同主机的多个容器间网络互通，走内网，类似于软件交换机
#networks:
#  gl-net:
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.0.0/16
#networks:
#  volume_gl-net:
#    external: true