version: '3.5'

services:
  mongo:
    image: mongo:4.4.11
    container_name: mongo
    command: [ "--bind_ip_all" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    restart: always
    #networks:
    #  gl-net:
    #    ipv4_address: 172.28.0.60
    volumes:
      - ./data:/data/db
      - ./log:/var/log/mongodb
    ports:
      - 27017:27017

#docker network ls
#The actual name is volume_gl-net
#表示新建了 `172.28.0.0/16` 的网络，名称为 gl-net
#新建网络是为了实现同主机的多个容器间网络互通，走内网，类似于软件交换机
#networks:
#  gl-net:
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.0.0/16
#networks:
#  volume_gl-net:
#    external: true